name: 'autoassign'
description: 'automatically assign stale PRs'
inputs:
  github_token:
    description: 'API Token for Github'
    required: true
  user_to_assign:
    description: 'user to assign'
    default: ${{ github.repository_owner }}
runs:
  using: "composite"
  steps:
    - name: "Autoassign"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
          curl -q --fail --retry 8 --header "Authorization: Bearer $GH_TOKEN" "${GITHUB_API_URL:-https://api.github.com}"/user | jq .login -r | xargs -I '{}' gh pr list --repo "$GITHUB_REPOSITORY" --state open --author '{}' --json number,headRefName | jq '.[] | [ .number, .headRefName ] | @tsv' | sed 's/\t/ /g' | while read -r number branch; do
            commit_date="$(gh api /repos/"$GITHUB_REPOSITORY"/commits?sha="$branch"'&'per_page=1 | jq '.[0].commit.committer.date' -r)"
            if [ "$(date -u -d "$commit_date" +%s)" -gt "$(date -u -d "$(date -u -d '3 days ago' '+%Y-%m-%dT%H:%M:%SZ')" +%s)" ]; then continue; fi
            gh pr edit "$number" --add-assignee ${{ inputs.user_to_assign }} --repo "$GITHUB_REPOSITORY"
          done
